version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgloader:
    image: dimitri/pgloader  # official pgloader image
    depends_on:
      - postgres
    volumes:
      - ./sqlite/data:/data  # where your SQLite db is mounted
    entrypoint: >
      bash -c "
      sleep 5 &&
      pgloader sqlite:///data/database.db postgresql://myuser:mypass@postgres/mydb
      "

volumes:
  pg_data:
