DISPLAY_REPORT_ID = "ContentPlaceHolder1_btnDisplay"
YEAR_SELECT_ID = "ContentPlaceHolder1_ddYear"
MUNI_SELECT_ID = "ContentPlaceHolder1_ddMuniId"
COUNTY_SELECT_ID = "ContentPlaceHolder1_ddCountyId"
BASE_URL = "https://apps.dced.pa.gov/munstats-public/ReportInformation2.aspx?report=mAfrForm"
